### ISSUE TITLE
Use a different combination than Control + M to toggle 

### ISSUE THREAD

**Issue by landland** [JackAdams/constellation#1]
I paid for meteor toys and already have it in a number of projects, but I really like the idea of the constellation plugins and would like to evaluate this some more. It already has plugins with some features that I like that meteor toys doesn't have. Would it be possible do use a different combination than Control + M to avoid having both meteor toys and constellation show up or at least make it configureable?

Also, I noticed the github link on atmosphere at https://atmospherejs.com/constellation/console points to the wrong repo (https://github.com/babrahams/constellation/ instead of https://github.com/JackAdams/constellation)

**Comment by JackAdams** [comment]
Hi @landland,
Very good point about not conflicting with meteor toys.  There will be a release with a default ctrl + C option to toggle the interface coming very soon and ctrl + M will have no effect. Because Constellation is all about configurability, I'll look into making this configurable too.
Thanks for the heads up about the wrong repo link too!
Brent

**Comment by JackAdams** [comment]
Okay. That's all in place in the latest release.  Docs mention how to configure if ctrl + C isn't the key you want.

**Comment by landland** [comment]
that was quick! thanks and keep up the great work.

**Comment by landland** [comment]
so I recently upgraded last night and I noticed it changed back to Control + M. I see the docs say Control + C in one part and Control + M in another. Is this a bug?

**Comment by JackAdams** [comment]
Thanks for spotting that typo in the docs.  It should only be CTRL + C.  Check your `.meteor/versions` file and make sure that it says `constellation:console@1.2.0`.  CTRL + M should only toggle Mongol/MeteorToys and should have no effect on Constellation.

**Comment by illmat** [comment]
CTRL + C collidates with the copy hotkey.  
Maybe not the best default value.

**Comment by JackAdams** [comment]
Haha... that's windows machines, right?  Should have remembered that.

Any suggestions?  If I pick something at random, I'll probably just hit another hotkey.

**Comment by JackAdams** [comment]
```
Package['constellation:console'].API.setKeyCode(71);
```

will make it CTRL + G.

But then you've got Constellation-specific code in your app so that's not really an acceptable solution ...

**Comment by illmat** [comment]
Hehe, actually it's Linux :penguin: 
Not sure about a good default key. ctrl + x/c/v are used by Linux/Windows.
Nearly all other characters besides 'm' are used by most browsers.
CTRL + g for example is used for 'find next' in chrome and firefox
Maybe CTRL + . or ,
