### ISSUE TITLE
How to change colors and remove transparency

### ISSUE THREAD

**Issue by repjackson** [JackAdams/constellation#14]
Whats the recommended way?  Specifically inside the doc window.  Thank you for the great package.

**Comment by JackAdams** [comment]
My suggestion would be to write a `debugOnly` package to add a theme to Constellation, containing a file to overwrite the default CSS rules.  The `debugOnly` will keep the package out of production apps.

[Here is an opaque theme](https://github.com/JackAdams/constellation-theme-opaque) that you can clone into your `/packages` directory, `meteor add constellation:theme-opaque`, and you'll have an opaque background.  You can then add CSS rules to the `.css` file in the package until the widget looks right.  If you like, you can change the package name and publish it, or submit a PR and I'll publish the finished version on atmosphere.

**Comment by repjackson** [comment]
Wow, impressive. Thanks Brent, will do.
