### ISSUE TITLE
Exception while invoking method 'Constellation_update'

### ISSUE THREAD

**Issue by tomyo** [JackAdams/constellation#19]
This happens when using the 'Update' option in a document.
I get a popup in the client saying there was a error, the document to update is not updated.
This is what I get in the server:
`Exception while invoking method 'Constellation_update' { stack: 'TypeError: Object  has no method \'contains\'\n    at packages/constellation_console/common/utility_functions.js:43:1\n    at arrayEach (/home/tomyo/.meteor/packages/stevezhu_lodash/.4.13.1.1yr23pl++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:451:11)\n    at Function.forEach (/home/tomyo/.meteor/packages/stevezhu_lodash/.4.13.1.1yr23pl++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:8634:14)\n    at Object.Constellation.diffDocumentData (packages/constellation_console/common/utility_functions.js:41:1)\n    at Object.Constellation.updateDocument (packages/constellation_console/common/mutators.js:82:1)\n    at [object Object].Meteor.methods.Constellation_update (packages/constellation_console/server/methods.js:9:1)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)\n    at packages/ddp-server/livedata_server.js:711:19\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)',
source: 'method' }
`

Using meteor@1.3.2.4

**Comment by JackAdams** [comment]
Weird.  It looks like you're using `stevezhu:lodash` to overwrite the `underscore` symbol, but the underscore symbol now doesn't have a `_.contains` method available.  Any chance I could take a look at your `/.meteor/packages` file?

**Comment by tomyo** [comment]
Yes, you got it right about `stevezhu:lodash` package, in fact, I override _ to lodash on startup, is that the problem?

Here's my packages file (any suggestion is welcome, sorry for all the comments inside):

```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

coffeescript
standard-minifier-css
standard-minifier-js
twbs:bootstrap
fortawesome:fontawesome

# Accounts
accounts-password
accounts-facebook
service-configuration
email

# Router and rendering
kadira:flow-router
kadira:blaze-layout
useraccounts:flow-routing
arillo:flow-router-helpers  # pathFor
meteorhacks:fast-render
meteorhacks:ssr  # Server side rendering
mdg:seo  # Galaxy uses prerender.io automatically when this package is installed

# Collections, schemas and forms
manuel:viewmodel
aldeed:collection2
matb33:collection-hooks  # before and after hooks
aldeed:autoform
nicolaslopezj:roles
meteorhacks:aggregate   # Add .aggregate to collections

# Admin and filesystem
orionjs:s3  # Testing and production storage
orionjs:bootstrap
orionjs:summernote
orionjs:relationships
orionjs:image-attribute
#nicolaslopezj:orion-rut-input

# Translations
gwendall:simple-schema-i18n
gwendall:autoform-i18n
softwarerero:accounts-t9n  # Translations for accounts package
orionjs:lang-es

# Test data generation
dburles:factory  # A package for creating test data or for generating fixtures
anti:fake  # Fake text and data generator

# Widgets and utilities
babrahams:constellation
rcy:nouislider  # Double slider for price range
stevezhu:lodash  # _ and lodash in scope (Warning: _ gets replace by meteor underscore sometimes, must override on startup)
sacha:spin  # Spinner
miguelalarcos:flow-router-pagination  # Pagination (local package)
natestrauser:select2  # select inputs with instant search box
aldeed:autoform-select2  # input select with search box, autoform.meteor.com/types
peerlibrary:assert
rzymek:moment-locale-es  # For handling time objects easily, in spanish
yasaricli:slugify  # slugify('String', 'separator')

# App analisis
meteorhacks:kadira  # Performance monitoring at kadira.io
kadira:debug
meteorhacks:kadira-profiler
fermuch:stats.js
```

**Comment by JackAdams** [comment]
Sorry, I've taken so long to get back to you about this.  I'm going to have to release a new version of Constellation with all the dependencies declared explicitly (and correctly). The `underscore` dependency is only declared on the client but is also used on the server.
