### ISSUE TITLE
0.4.6 not compatible with meteor 1.4.1.1

### ISSUE THREAD

**Issue by tomyo** [JackAdams/constellation#20]
I'm trying to update from 0.4.5 to 0.4.6 in Meteor 1.4.1.1, this is what I get:

```
The following top-level dependencies were not updated to the very latest version available:
 * babrahams:constellation 0.4.5 (0.4.6 is available)

```

```
meteor update babrahams:constellation
The specified packages are at their latest compatible versions.

```

**Comment by JackAdams** [comment]
Yeah, there might me some dependencies of that package that haven't been updated.

Try: meteor update babrahams:constellation

**Comment by JackAdams** [comment]
Sorry, it looks like I didn't read your comment carefully enough the first time. I see now that `meteor update babrahams:constellation` gives you the "... latest compatible versions." message.

I've got `babrahams:constellation` 0.4.6 running on a couple of different apps at 1.4.1.1 with no problems. I know it's hard to do a minimal repro these days with no Meteorpad, but that would help get to the bottom of the issue.

**Comment by JackAdams** [comment]
I've removed some of the dependencies that might have been causing this.
