### ISSUE TITLE
Where are the docs for accessing this functionality?

### ISSUE THREAD

**Issue by conradwt** [JackAdams/constellation#21]
Hi, I have been searching for the docs for accessing this functionality of this project within a Meteor application.  At this time, it only tells me to type Control-C but it's not clear where you want people to type.

**Comment by JackAdams** [comment]
`meteor add constellation:console` (or `babrahams:constellation`, for more functionality). Then, when your app is running, you should be able the press control+c to open the dev console. If you add `babrahams:constellation`, you should get a blue dot in the corner of your app (in development only) and you can click on that to open the dev console.

Have a look at the demo at http://constellation.taonova.com to see how it works.

**Comment by conradwt** [comment]
@JackAdams Yes, I found the blue dot in the lower left hand of the screen.  Thanks for the information.
