### ISSUE TITLE
Update dependencies for meteor 1.6.1

### ISSUE THREAD

**Issue by stratosgear** [JackAdams/constellation#22]
Is it possible to update this package for the latest Meteor version?

I get some conflicts with `aldeed:collection2` that I cannot resolve.

Thanks!

**Comment by JackAdams** [comment]
I'm currently using it with 1.6.1, but that's working because this package uses the last version of `aldeed:collection2` that was published to atmosphere, same as the apps I'm working on.  Are you adding `collection2` via npm?

**Comment by stratosgear** [comment]
Hmmm, that's exactly how I load `collection2` through the `.meteor/packages` file.  As a matter of fact here is all my packages:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

less@2.7.11
iron:router
fortawesome:fontawesome
momentjs:moment
meteor-base@1.3.0
mobile-experience@1.0.5
mongo@1.4.2
blaze-html-templates@1.0.4
session@1.1.7
tracker@1.1.3
logging@1.1.19
reload@1.2.0
random@1.1.0
ejson@1.1.0
spacebars@1.0.12
check@1.3.0
okgrow:router-autoscroll
dbarrett:dropzonejs
standard-minifier-css@1.4.0
standard-minifier-js@2.3.1
shell-server@0.3.1
es5-shim@4.7.0
ecmascript@0.10.0
reactive-var@1.0.11
fourseven:scss
tsega:bootstrap3-datetimepicker
jquery@1.11.10
dynamic-import@0.3.0
d3js:d3
russ:weather-icons
aldeed:collection2@3.0.0
aldeed:autoform
msavin:mongol
msavin:jetsetter
msgfmt:core
msgfmt:extract 
msgfmt:ui-dev-only
accounts-ui
accounts-google
accounts-password
google-config-ui
```

When I add `constellation:console` in that packages files and run `meteor update` I get:

```
$ meteor update
This project is already at Meteor 1.6.1, the latest release.
=> Errors while upgrading packages:           
                                              
While selecting package versions:
error: Conflict: Constraint aldeed:collection2@2.9.1 is not satisfied by aldeed:collection2 3.0.0.
Constraints on package "aldeed:collection2":
* aldeed:collection2@3.0.0 <- top level
* aldeed:collection2@3.0.0 <- aldeed:autoform 6.3.0
* aldeed:collection2@2.9.1 <- babrahams:editable-json 0.6.4 <- constellation:console 1.4.5
* aldeed:collection2@2.10.0 <- constellation:console 1.4.5

Conflict: Constraint aldeed:collection2@2.10.0 is not satisfied by aldeed:collection2 3.0.0.
Constraints on package "aldeed:collection2":
* aldeed:collection2@3.0.0 <- top level
* aldeed:collection2@3.0.0 <- aldeed:autoform 6.3.0
* aldeed:collection2@2.9.1 <- babrahams:editable-json 0.6.4 <- constellation:console 1.4.5
* aldeed:collection2@2.10.0 <- constellation:console 1.4.5
```

Is there another way to inlude the package...?

Sorry, I'm not that familiar with installing from npm, and I only use the suggested way by the meteor tutorials, and only update the `packages` and then run `meteor update` from the commandline.  

Being such a newbie, I really need to get some of these debug packages up and running so any help would be greatly appreciated. Thanks!

**Comment by stratosgear** [comment]
Forgot to mention that running `meteor update --all-packages` or `meteor update --allow-incompatible-update` does not seem to help either.

**Comment by JackAdams** [comment]
Yep. I'm working on this. I'll try to publish a compatible version soon. The change of version of `aldeed:collection2` from `2.10.0` to `3.0.0` was quite significant, so it's taking a bit of work.

**Comment by JackAdams** [comment]
I've removed the weak dependencies on `aldeed:collection2` from the `constellation` packages. Trying updating using `meteor update` now.
