### ISSUE TITLE
Console position

### ISSUE THREAD

**Issue by ay13** [JackAdams/constellation#7]
Add the ability to change the console position on the screen.

Examples:
lower right
off canvas slide in would be cool

**Comment by JackAdams** [comment]
Yes, I've been thinking about this.  It just needs a package that overwrites some CSS and adds a way to trigger the slide in / slide out.

**Comment by JackAdams** [comment]
https://github.com/JackAdams/constellation-position

```
meteor add constellation:position
```

This package gives some basic four-corners functionality, but no slide-in / slide-out.  Feel free to fork and improve it.
